vich_uploader:
    db_driver: orm

    mappings:
        song_image:
            uri_prefix: /songs/images
            upload_destination: '%kernel.project_dir%/public/songs/images'
            namer:  Vich\UploaderBundle\Naming\UniqidNamer

        song_file:
            uri_prefix: /songs/files
            upload_destination: '%kernel.project_dir%/public/songs/files'
            namer:  Vich\UploaderBundle\Naming\UniqidNamer
    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
